-- MySQL Script generated by MySQL Workbench
-- Fri Sep  4 22:17:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hostel_gestao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hostel_gestao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hostel_gestao` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `hostel_gestao` ;

-- -----------------------------------------------------
-- Table `hostel_gestao`.`responsaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`responsaveis` (
  `id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `contacto` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`clientes` (
  `id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `tipo_documento` ENUM('Cartão de Cidadão', 'Passaporte', 'Título de Residência', 'Outro') NOT NULL,
  `numero_documento` VARCHAR(50) NOT NULL,
  `nif` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `morada` VARCHAR(255) NULL DEFAULT NULL,
  `nacionalidade` VARCHAR(100) NULL DEFAULT NULL,
  `estado_civil` VARCHAR(30) NULL DEFAULT NULL,
  `data_nascimento` DATE NOT NULL,
  `validade_documento` DATE NOT NULL,
  `contacto_emergencia` VARCHAR(150) NULL DEFAULT NULL,
  `incompleto` TINYINT(1) NOT NULL DEFAULT '0',
  `anonimizado` TINYINT(1) NOT NULL DEFAULT '0',
  `data_anonimizado` DATE NULL DEFAULT NULL,
  `responsavel_anonimizado_id` VARCHAR(10) NULL DEFAULT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `responsavel_anonimizado_id` (`responsavel_anonimizado_id` ASC) VISIBLE,
  CONSTRAINT `clientes_ibfk_1`
    FOREIGN KEY (`responsavel_anonimizado_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`configuracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`configuracoes` (
  `chave` VARCHAR(60) NOT NULL,
  `valor` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`chave`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`configuracoes_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`configuracoes_historico` (
  `id` VARCHAR(20) NOT NULL,
  `chave` VARCHAR(60) NOT NULL,
  `valor_anterior` VARCHAR(255) NOT NULL,
  `valor_novo` VARCHAR(255) NOT NULL,
  `data` DATE NOT NULL,
  `responsavel_id` VARCHAR(10) NOT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `chave` (`chave` ASC) VISIBLE,
  INDEX `responsavel_id` (`responsavel_id` ASC) VISIBLE,
  CONSTRAINT `configuracoes_historico_ibfk_1`
    FOREIGN KEY (`chave`)
    REFERENCES `hostel_gestao`.`configuracoes` (`chave`),
  CONSTRAINT `configuracoes_historico_ibfk_2`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`requisicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`requisicoes` (
  `id` VARCHAR(10) NOT NULL,
  `responsavel_id` VARCHAR(10) NOT NULL,
  `estado` ENUM('pendente', 'enviada', 'fechada', 'rejeitada') NOT NULL DEFAULT 'pendente',
  `data_pedido` DATE NOT NULL,
  `data_envio` DATE NULL DEFAULT NULL,
  `data_fecho` DATE NULL DEFAULT NULL,
  `responsavel_rejeicao_id` VARCHAR(10) NULL DEFAULT NULL,
  `motivo_rejeicao` VARCHAR(255) NULL DEFAULT NULL,
  `observacoes` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `responsavel_id` (`responsavel_id` ASC) VISIBLE,
  INDEX `responsavel_rejeicao_id` (`responsavel_rejeicao_id` ASC) VISIBLE,
  CONSTRAINT `requisicoes_ibfk_1`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`),
  CONSTRAINT `requisicoes_ibfk_2`
    FOREIGN KEY (`responsavel_rejeicao_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`devolucoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`devolucoes` (
  `id` VARCHAR(10) NOT NULL,
  `requisicao_id` VARCHAR(10) NOT NULL,
  `responsavel_id` VARCHAR(10) NOT NULL,
  `estado` ENUM('pendente', 'fechada') NOT NULL DEFAULT 'pendente',
  `data_reportada` DATE NOT NULL,
  `data_fecho` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `requisicao_id` (`requisicao_id` ASC) VISIBLE,
  INDEX `responsavel_id` (`responsavel_id` ASC) VISIBLE,
  CONSTRAINT `devolucoes_ibfk_1`
    FOREIGN KEY (`requisicao_id`)
    REFERENCES `hostel_gestao`.`requisicoes` (`id`),
  CONSTRAINT `devolucoes_ibfk_2`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`produtos` (
  `id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `unidade_medida` VARCHAR(30) NOT NULL,
  `stock_minimo` INT NOT NULL DEFAULT '0',
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`itens_devolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`itens_devolucao` (
  `id` VARCHAR(10) NOT NULL,
  `devolucao_id` VARCHAR(10) NOT NULL,
  `produto_id` VARCHAR(10) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `devolucao_id` (`devolucao_id` ASC) VISIBLE,
  INDEX `produto_id` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `itens_devolucao_ibfk_1`
    FOREIGN KEY (`devolucao_id`)
    REFERENCES `hostel_gestao`.`devolucoes` (`id`),
  CONSTRAINT `itens_devolucao_ibfk_2`
    FOREIGN KEY (`produto_id`)
    REFERENCES `hostel_gestao`.`produtos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`itens_requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`itens_requisicao` (
  `id` VARCHAR(10) NOT NULL,
  `requisicao_id` VARCHAR(10) NOT NULL,
  `produto_id` VARCHAR(10) NOT NULL,
  `quantidade_pedida` INT NOT NULL,
  `quantidade_enviada` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `requisicao_id` (`requisicao_id` ASC) VISIBLE,
  INDEX `produto_id` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `itens_requisicao_ibfk_1`
    FOREIGN KEY (`requisicao_id`)
    REFERENCES `hostel_gestao`.`requisicoes` (`id`),
  CONSTRAINT `itens_requisicao_ibfk_2`
    FOREIGN KEY (`produto_id`)
    REFERENCES `hostel_gestao`.`produtos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`propriedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`propriedades` (
  `id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `morada` VARCHAR(255) NULL DEFAULT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`unidades` (
  `id` VARCHAR(10) NOT NULL,
  `propriedade_id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `tipo` ENUM('mensal', 'airbnb') NOT NULL,
  `preco_base` DECIMAL(10,2) NOT NULL,
  `preco_epoca_alta` DECIMAL(10,2) NOT NULL,
  `multa_check_in_tardio` DECIMAL(10,2) NOT NULL,
  `epoca_alta_ativa` TINYINT(1) NOT NULL DEFAULT '0',
  `em_manutencao` TINYINT(1) NOT NULL DEFAULT '0',
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `propriedade_id` (`propriedade_id` ASC) VISIBLE,
  CONSTRAINT `unidades_ibfk_1`
    FOREIGN KEY (`propriedade_id`)
    REFERENCES `hostel_gestao`.`propriedades` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`quartos` (
  `id` VARCHAR(10) NOT NULL,
  `unidade_id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `privativo` TINYINT(1) NOT NULL DEFAULT '0',
  `limpeza_incluida` TINYINT(1) NOT NULL DEFAULT '0',
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `unidade_id` (`unidade_id` ASC) VISIBLE,
  CONSTRAINT `quartos_ibfk_1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `hostel_gestao`.`unidades` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`lugares` (
  `id` VARCHAR(10) NOT NULL,
  `quarto_id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `capacidade` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `quarto_id` (`quarto_id` ASC) VISIBLE,
  CONSTRAINT `lugares_ibfk_1`
    FOREIGN KEY (`quarto_id`)
    REFERENCES `hostel_gestao`.`quartos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`movimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`movimentos` (
  `id` VARCHAR(10) NOT NULL,
  `produto_id` VARCHAR(10) NOT NULL,
  `tipo` ENUM('entrada', 'saida', 'ajuste') NOT NULL,
  `quantidade` INT NOT NULL,
  `data` DATE NOT NULL,
  `responsavel_id` VARCHAR(10) NULL DEFAULT NULL,
  `requisicao_id` VARCHAR(10) NULL DEFAULT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `produto_id` (`produto_id` ASC) VISIBLE,
  INDEX `responsavel_id` (`responsavel_id` ASC) VISIBLE,
  INDEX `requisicao_id` (`requisicao_id` ASC) VISIBLE,
  CONSTRAINT `movimentos_ibfk_1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `hostel_gestao`.`produtos` (`id`),
  CONSTRAINT `movimentos_ibfk_2`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`),
  CONSTRAINT `movimentos_ibfk_3`
    FOREIGN KEY (`requisicao_id`)
    REFERENCES `hostel_gestao`.`requisicoes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`ocupacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`ocupacoes` (
  `id` VARCHAR(10) NOT NULL,
  `unidade_id` VARCHAR(10) NOT NULL,
  `cliente_id` VARCHAR(10) NOT NULL,
  `tipo` ENUM('mensal', 'airbnb') NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `lugar_id` VARCHAR(10) NULL DEFAULT NULL,
  `aviso_documento` TINYINT(1) NOT NULL DEFAULT '0',
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `unidade_id` (`unidade_id` ASC) VISIBLE,
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `lugar_id` (`lugar_id` ASC) VISIBLE,
  CONSTRAINT `ocupacoes_ibfk_1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `hostel_gestao`.`unidades` (`id`),
  CONSTRAINT `ocupacoes_ibfk_2`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `hostel_gestao`.`clientes` (`id`),
  CONSTRAINT `ocupacoes_ibfk_3`
    FOREIGN KEY (`lugar_id`)
    REFERENCES `hostel_gestao`.`lugares` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`ocupacoes_airbnb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`ocupacoes_airbnb` (
  `ocupacao_id` VARCHAR(10) NOT NULL,
  `preco_calculado` DECIMAL(10,2) NOT NULL,
  `preco_praticado` DECIMAL(10,2) NOT NULL,
  `responsavel_desconto_preco_id` VARCHAR(10) NULL DEFAULT NULL,
  `check_in_tardio` TINYINT(1) NOT NULL DEFAULT '0',
  `hora_chegada` TIME NULL DEFAULT NULL,
  `multa_calculada` DECIMAL(10,2) NOT NULL,
  `multa_praticada` DECIMAL(10,2) NOT NULL,
  `responsavel_desconto_multa_id` VARCHAR(10) NULL DEFAULT NULL,
  `motivo_cancelamento` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ocupacao_id`),
  INDEX `responsavel_desconto_preco_id` (`responsavel_desconto_preco_id` ASC) VISIBLE,
  INDEX `responsavel_desconto_multa_id` (`responsavel_desconto_multa_id` ASC) VISIBLE,
  CONSTRAINT `ocupacoes_airbnb_ibfk_1`
    FOREIGN KEY (`ocupacao_id`)
    REFERENCES `hostel_gestao`.`ocupacoes` (`id`),
  CONSTRAINT `ocupacoes_airbnb_ibfk_2`
    FOREIGN KEY (`responsavel_desconto_preco_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`),
  CONSTRAINT `ocupacoes_airbnb_ibfk_3`
    FOREIGN KEY (`responsavel_desconto_multa_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hostel_gestao`.`ocupacoes_mensal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostel_gestao`.`ocupacoes_mensal` (
  `ocupacao_id` VARCHAR(10) NOT NULL,
  `renda_calculada` DECIMAL(10,2) NOT NULL,
  `renda_praticada` DECIMAL(10,2) NOT NULL,
  `responsavel_desconto_renda_id` VARCHAR(10) NULL DEFAULT NULL,
  `caucao` DECIMAL(10,2) NOT NULL,
  `caucao_exige_confirmacao` TINYINT(1) NOT NULL DEFAULT '0',
  `motivo_alteracao_renda` VARCHAR(255) NULL DEFAULT NULL,
  `motivo_alteracao_caucao` VARCHAR(255) NULL DEFAULT NULL,
  `dia_vencimento` INT NOT NULL,
  `motivo_encerramento` VARCHAR(255) NULL DEFAULT NULL,
  `duracao_abaixo_minima` TINYINT(1) NOT NULL DEFAULT '0',
  `aviso_previo_insuficiente` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ocupacao_id`),
  INDEX `responsavel_desconto_renda_id` (`responsavel_desconto_renda_id` ASC) VISIBLE,
  CONSTRAINT `ocupacoes_mensal_ibfk_1`
    FOREIGN KEY (`ocupacao_id`)
    REFERENCES `hostel_gestao`.`ocupacoes` (`id`),
  CONSTRAINT `ocupacoes_mensal_ibfk_2`
    FOREIGN KEY (`responsavel_desconto_renda_id`)
    REFERENCES `hostel_gestao`.`responsaveis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
